### ISSUE TITLE
Add support for infinispan stats

### ISSUE THREAD

**Issue by jcode** [torquebox/backstage#32]
Is ultra important to have visibility to metrics like:

-cache object number
-get
-puts
-hit rate
-%mem used

It would be great to have something... i don't know if it is possible.

**Comment by swistaczek** [comment]
Hey @jcode, did you come up with any solution for this problem?

**Comment by jcode** [comment]
No :( We ended up using memcache again (sharing the VM memory space between the app and the cache didn't work for us)
